name: Deploy

on:
  push:
    branches:
      - '*'

jobs:
  deploy:
    name: Test, Build, Deploy
    runs-on: ubuntu-latest
    env:
      GITHUB_HEAD_REF: ${{ github.ref }}

    steps:
    - name : "Deploytag"
      uses: opszero/deploytag@v3.0.1
      id: deploytag

    - name: Checkout
      uses: actions/checkout@v2

