name: Deploy

on:
  push:
    branches:
      - '**'

jobs:
  deploy:
    name: Test, Build, Deploy
    runs-on: ubuntu-latest

    steps:
    - name : "Deploytag"
      uses: thaunghtike-share/deploytag@v.10
      id: deploytag

    - name: Checkout
      uses: actions/checkout@v2

    - name: Install Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1-node16
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-west-2
