name: Deploy

on:
  push:
    branches:
      - '*'

jobs:
  deploy:
    name: Test, Build, Deploy
    runs-on: ubuntu-latest

    steps:
    - name : "Deploytag"
      uses: thaunghtike-share/actions-deploytag@master
      id: deploytag

    - name: Checkout
      uses: actions/checkout@v2-node16

