name: Deploy

on:
  push:
    branches:
      - '**'

jobs:
  deploy:
    name: Test, Build, Deploy
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      
    - name : "Deploytag"
      uses: thaunghtike-share/actions-deploytag@master
      id: deploytag

    - name: Install Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
